apiVersion: v1
kind: Service
metadata:
  name: api-gw-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::051577428978:server-certificate/CERT_NAME
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https" ##only allow ssl for https
spec:
  type: LoadBalancer
  selector:
    app: api-gw
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: http2
    port: 80
    targetPort: 8080
    protocol: TCP

